export const HACKATHON_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
};

export const TRACK_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
};

export const ROUND_TIEBREAK_RULE = {
  PENALTY_SCORE: 'PENALTY_SCORE',
  LATEST_SUBMISSION: 'LATEST_SUBMISSION',
  EARLIEST_SUBMISSION: 'EARLIEST_SUBMISSION',
};
